import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Gallery App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

function TopNav(){
  return (
    <nav className="flex w-full items-center justify-between border-b p-4 text-xl font-semibold text-white">
     <div>Gallery</div>
     <div>Sign In</div>
    </nav>
  )
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable} flex flex-col gap-3`}>
      
      <body>
        <TopNav />
        {children}
        </body>
    </html>
  );
}
